### PR TITLE
Added way to get timeline of sentiments

### PR DESCRIPTION
**Pull request by jmhossler**

### CODE REVIEW

**Comment by jmhossler** [comment]
get_moods is returning a list of tuples with a sentiment and epoch_time attribute. epoch_time is the number of seconds since epoch (it's an integer value), and sentiment is the same thing we had before: a tuple with a .polarity and .subjectivity attribute.

**Comment by tlmurphy** [comment]
What should I be using the epoch for?

**Comment by jmhossler** [comment]
for the x axis of the graph. epoch is the time for each mood.

**Comment by tlmurphy** [comment]
So basically `get_moods()` is doing the same thing as `get_mood()` but with just a timestamp added on?

**Comment by jmhossler** [comment]
yes. Basically. still need to add the ability to get more than 100 tweets, but I figured that could be added later (this weekend).

**Pull request merged**
